"use client"

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { CopyableId } from "@/components/copyable-id"
import { formatSui } from "@/lib/format"
import { useMandateStore } from "@/lib/mandate-store"

function executionTime(timestamp: number) {
  const diffMs = Date.now() - timestamp
  if (!Number.isFinite(timestamp) || diffMs < 60_000) {
    return "just now"
  }

  const mins = Math.floor(diffMs / 60_000)
  if (mins < 60) {
    return `${mins}m ago`
  }

  const hours = Math.floor(diffMs / 3_600_000)
  if (hours < 24) {
    return `${hours}h ago`
  }

  return `${Math.floor(hours / 24)}d ago`
}

export function OrdersView() {
  const { orders } = useMandateStore()

  return (
    <Card>
      <CardHeader className="border-b border-border">
        <CardTitle>DeepBook execution history</CardTitle>
        <CardDescription>
          Real execution records generated by successful Run Agent PTBs.
        </CardDescription>
      </CardHeader>
      <CardContent className="p-0">
        {orders.length > 0 ? (
          <Table>
            <TableHeader>
              <TableRow className="border-border hover:bg-transparent">
                <TableHead className="pl-4">Mandate</TableHead>
                <TableHead>Digest</TableHead>
                <TableHead>Protocol</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">SUI Balance Change</TableHead>
                <TableHead className="hidden pr-4 text-right md:table-cell">
                  Time
                </TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {orders.map((execution) => (
                <TableRow key={execution.id} className="border-border">
                  <TableCell className="pl-4">
                    <div className="flex flex-col gap-0.5">
                      <span className="font-medium">
                        {execution.mandateLabel}
                      </span>
                      <CopyableId
                        value={execution.mandateId}
                        label="mandate id"
                        className="text-xs text-muted-foreground"
                      />
                    </div>
                  </TableCell>
                  <TableCell>
                    <CopyableId value={execution.digest} label="digest" />
                  </TableCell>
                  <TableCell>{execution.protocol}</TableCell>
                  <TableCell>
                    <Badge
                      variant="outline"
                      className="border-emerald-500/25 bg-emerald-500/10 font-medium capitalize text-emerald-400"
                    >
                      {execution.status}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-right font-mono text-sm tabular-nums">
                    {typeof execution.suiBalanceChange === "number"
                      ? formatSui(execution.suiBalanceChange)
                      : "-"}
                  </TableCell>
                  <TableCell className="hidden pr-4 text-right text-sm text-muted-foreground tabular-nums md:table-cell">
                    {executionTime(execution.timestamp)}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        ) : (
          <div className="flex flex-col items-center gap-2 px-6 py-16 text-center">
            <p className="text-sm font-medium text-foreground">
              No DeepBook executions yet.
            </p>
            <p className="max-w-md text-sm text-muted-foreground">
              Run an agent with an active mandate to generate real execution
              history.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
